name: kigali_price_check_mobile
description: "A crowdsourced platform for real-time price comparison in Rwanda"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.3.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5

  # Firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6

  # Navigation
  go_router: ^10.1.2

  # UI Components
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3

  # Phone Authentication
  pin_code_fields: ^8.0.1

  # Social Authentication
  google_sign_in: ^6.1.4

  # Form Validation
  form_validator: ^2.1.1

  # Utilities
  intl: ^0.18.1
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/fonts/
    - assets/animations/

  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf